### ISSUE TITLE
meme-cli update-sources not working

### ISSUE THREAD

**Issue by harisahmed05** [TheRawMeatball/meme-cli#1]
Hi! 
First of all, thanks for making something **_cool_** like that!

I'm facing an issue while updating sources:
`Updating meme repository default (https://github.com/TheRawMeatball/memeinator-memesrc.git)
fatal: not a git repository (or any of the parent directories): .git
Error: Git error!`

I installed `meme-cli` by using `cargo`. 
My git version: `2.34.1`

Please help!

**Comment by TheRawMeatball** [comment]
What OS are you on? If you're on linux, can you try deleting `~/.cache/memecli` and updating again?

**Comment by harisahmed05** [comment]
I'm using Arch. Thanks, that worked! <3

**Comment by Dentrax** [comment]
@TheRawMeatball Hey! Does not work on me:

```
$ meme-cli update-sources

Updating meme repository default (https://github.com/TheRawMeatball/memeinator-memesrc.git)
fatal: not a git repository (or any of the parent directories): .git
Error: Git error!
```

```
$ meme-cli --version
meme-cli 0.1.2
```

`macOS 11`

There is no `~/.cache/memecli` folder. Anythink should I need to do?

**Comment by TheRawMeatball** [comment]
For macOS, it should be `~/Library/Caches/memecli`
Try deleting that?

**Comment by Dentrax** [comment]
> `$ ~/Library/Caches/memecli`

Thanks! Works like a charm!

**Comment by h33p** [comment]
The bug seems to happen when an empty `default` gets created automatically, before sources get refreshed.
