### ISSUE TITLE
feature `edition2021` is required

### ISSUE THREAD

**Issue by petski** [TheRawMeatball/meme-cli#11]
Got a lot of <code>feature `edition2021` is required; consider adding `cargo-features = ["edition2021"]` to the manifest</code> messages when trying to build.

Seems needed for:
- `Cargo.toml`
- `meme-bevy/Cargo.toml`
- `memeinator/Cargo.toml`

**Comment by TheRawMeatball** [comment]
Edition 2021 is available without any extra additions for recent versions. Make sure your rust is up-to-date.
