### ISSUE TITLE
fuzzy or "contains" matching in `meme-cli generate`

### ISSUE THREAD

**Issue by jakobhellermann** [TheRawMeatball/meme-cli#16]
It would be useful if you could do `meme-cli generate winnie` instead of doing `meme-cli list-templates`, find the correct one, use `meme-cli generate tuxedo-winnie-the-pooh`.

**Comment by TheRawMeatball** [comment]
This is more so the domain of whatever shell you're using. Adding completions can make `meme-cli generate winnie` expand to `meme-cli generate tuxedo-winnie-the-pooh`
