### ISSUE TITLE
Where is the sources downloaded to?

### ISSUE THREAD

**Issue by themisir** [TheRawMeatball/meme-cli#2]
I messed up with update-sources by terminating `git clone` with SIGTERM. In which directory does meme-cli clones source repository to so I could try to repair it or remove to make it clone source again.

Thanks!

```
MacOS 12.0 / rustc 1.56.1 / meme-cli 0.1.2
```

**Comment by TheRawMeatball** [comment]
The meme repositories are cloned to the `memecli` folder in your cache folder. So, for MacOS it should be `~/Library/Caches/memecli`

**Comment by themisir** [comment]
> ~/Library/Caches/memecli

Thank you! Also I think it might be faster to clone sources using `--depth 1` argument cause I don't see any reason it would need to see previous git history.

**Comment by TheRawMeatball** [comment]
Hm, I'm not that familiar with all the fancy settings git offers, I'll take a look :) Marking this issue as closed for now though.

**Comment by themisir** [comment]
> Hm, I'm not that familiar with all the fancy settings git offers, I'll take a look :) Marking this issue as closed for now though.

Sure. By the way by default when you clone repository, git pulls snapshots related to all the previous commits, not just last one. With `--depth` option you can specify number of commits starting from HEAD you want to pull. Unless you want to see previous updates through git log doing `--depth 1` will increase cloning speed (this will be noticable when repository history becomes bigger) as it will just pull latest snapshot of the files only.
